# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='quest\xe3o', max_length=4000),
            preserve_default=False,
        ),
    ]
