# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0002_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_content', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
