# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mydidata.Choice'),
            preserve_default=False,
        ),
    ]
