# Generated by Django 2.0.2 on 2019-10-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0004_discursiveanswer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='discursiveanswer',
            name='file_required',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
