# Generated by Django 2.0.2 on 2019-10-13 20:01

import django.core.validators
from django.db import migrations, models
import mydidata.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0005_discursiveanswer_file_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discursiveanswer',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, storage=mydidata.storage_backends.PublicMediaStorage(), upload_to='assignments/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
