# Generated by Django 2.0.2 on 2019-10-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0006_auto_20191013_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='file_required',
        ),
    ]
