# Generated by Django 2.0.2 on 2019-10-13 21:38

from django.db import migrations, models
import mydidata.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0007_remove_discursiveanswer_file_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='discursiveanswer',
            name='file_types',
            field=models.CharField(max_length=255, null=True, verbose_name='Types'),
        ),
        migrations.AlterField(
            model_name='discursiveanswer',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, storage=mydidata.storage_backends.PublicMediaStorage(), upload_to='assignments/%Y/%m/%d'),
        ),
    ]
