# Generated by Django 2.0.2 on 2019-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0008_auto_20191013_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='discursiveanswer',
            name='text_required',
            field=models.BooleanField(default=False),
        ),
    ]
