# Generated by Django 2.0.2 on 2019-10-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0009_discursiveanswer_text_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='file_types',
        ),
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='text_required',
        ),
        migrations.AddField(
            model_name='question',
            name='file_types_accepted',
            field=models.CharField(max_length=255, null=True, verbose_name='Types'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_required',
            field=models.BooleanField(default=False),
        ),
    ]
