# Generated by Django 2.0.2 on 2019-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0010_auto_20191014_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file_types_accepted',
            field=models.CharField(blank='True', max_length=255, null=True, verbose_name='Types'),
        ),
    ]
