# Generated by Django 2.0.2 on 2019-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0011_auto_20191014_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='closed_topics',
            field=models.ManyToManyField(null=True, to='mydidata.Topic'),
        ),
    ]
