# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0012_auto_20171207_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 18, 32, 26, 222039, tzinfo=utc)),
        ),
    ]
