# Generated by Django 2.0.2 on 2019-10-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0012_classroom_closed_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='discursiveanswer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enviada'), (2, 'Correta'), (3, 'Incorreta'), (4, 'Reenviada')], default=1),
        ),
    ]
