# Generated by Django 2.0.2 on 2019-10-21 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0013_discursiveanswer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Classroom')),
                ('students', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='is_resource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourceroom',
            name='topics',
            field=models.ManyToManyField(null=True, to='mydidata.Topic'),
        ),
    ]
