# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0014_auto_20171207_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_on',
        ),
    ]
