# Generated by Django 2.0.2 on 2019-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0014_auto_20191021_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceroom',
            options={'verbose_name_plural': 'Turmas de Reforço'},
        ),
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enviada'), (2, 'Correta'), (3, 'Incorreta'), (4, 'Reenviada')], default=1),
        ),
    ]
