# Generated by Django 2.0.2 on 2019-10-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0015_auto_20191022_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='is_correct',
        ),
    ]
