# Generated by Django 2.0.2 on 2019-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0016_remove_discursiveanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
