# Generated by Django 2.0.2 on 2019-10-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0017_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
