# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0017_remove_question_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Exerc\xedcio'), (2, 'Trabalho'), (3, 'Prova')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dif\xedcil'), (2, 'M\xe9dio'), (3, 'F\xe1cil')]),
        ),
    ]
