# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0018_auto_20171208_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
