# Generated by Django 2.0.2 on 2019-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0018_topic_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Tópicos'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.AddField(
            model_name='classroom',
            name='closed_tests',
            field=models.ManyToManyField(null=True, to='mydidata.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(null=True, to='mydidata.Test', verbose_name='Tests'),
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
