# Generated by Django 2.0.2 on 2019-10-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0019_auto_20191023_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='tests',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
