# Generated by Django 2.0.2 on 2019-10-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0020_auto_20191023_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_assessment',
        ),
        migrations.AddField(
            model_name='classroom',
            name='tests',
            field=models.ManyToManyField(null=True, to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='closed_tests',
            field=models.ManyToManyField(null=True, related_name='closed_tests', to='mydidata.Test'),
        ),
    ]
