# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 01:25
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0020_auto_20171212_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
