# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 22:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0021_auto_20171213_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.CreateModel(
            name='DiscursiveAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydidata.Answer')),
                ('answer_text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            bases=('mydidata.answer',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydidata.Answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Choice')),
            ],
            bases=('mydidata.answer',),
        ),
        migrations.AddField(
            model_name='question',
            name='is_discursive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
