# Generated by Django 2.0.2 on 2019-10-24 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0021_auto_20191023_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='closed_tests',
            field=models.ManyToManyField(blank=True, related_name='closed_tests', to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='closed_topics',
            field=models.ManyToManyField(blank=True, to='mydidata.Topic'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='tests',
            field=models.ManyToManyField(blank=True, to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Topic'),
        ),
    ]
