# Generated by Django 2.0.2 on 2019-10-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0022_auto_20191023_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='tests',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='closed_tests',
            field=models.ManyToManyField(null=True, to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='closed_topics',
            field=models.ManyToManyField(null=True, to='mydidata.Topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Topic'),
        ),
    ]
