# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0022_auto_20171216_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('difficulty_level', models.PositiveSmallIntegerField(choices=[(1, 'Dif\xedcil'), (2, 'M\xe9dio'), (3, 'F\xe1cil'), (4, 'Misto')])),
                ('questions', models.ManyToManyField(to='mydidata.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mydidata.Test'),
            preserve_default=False,
        ),
    ]
