# Generated by Django 2.0.2 on 2019-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0023_auto_20191025_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='closed_tests',
            field=models.ManyToManyField(blank=True, null=True, related_name='closed_tests', to='mydidata.Test'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='closed_topics',
            field=models.ManyToManyField(blank=True, null=True, to='mydidata.Topic'),
        ),
    ]
