# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0023_auto_20171219_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydidata.Test'),
        ),
    ]
