# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0024_auto_20171220_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mydidata.Choice'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DiscursiveAnswer',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceAnswer',
        ),
    ]
