# Generated by Django 2.0.2 on 2019-11-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0024_auto_20191025_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
