# Generated by Django 2.0.2 on 2019-11-12 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0026_auto_20191101_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_list', models.CharField(max_length=255, verbose_name='índices')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Test')),
            ],
            options={
                'verbose_name_plural': 'Índices de Questões',
            },
        ),
    ]
