# Generated by Django 2.0.2 on 2019-11-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0027_testuserrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuserrelation',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
