# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0027_auto_20171222_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'T\xf3picos'},
        ),
        migrations.AddField(
            model_name='topic',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydidata.Discipline'),
        ),
    ]
