# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0029_auto_20180118_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydidata.Test')),
            ],
        ),
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='test',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='test',
        ),
        migrations.AddField(
            model_name='discursiveanswer',
            name='answer_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydidata.Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydidata.Answer'),
            preserve_default=False,
        ),
    ]
