# Generated by Django 2.0.2 on 2019-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0029_auto_20191122_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='key',
            field=models.CharField(default='testkey', max_length=200, verbose_name='Frase de Envio'),
        ),
    ]
