# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0030_auto_20180118_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='discursiveanswer',
            options={'verbose_name_plural': 'Respostas Discursivas'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoiceanswer',
            options={'verbose_name_plural': 'Respostas de M\xfaltipla Escolha'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Quest\xf5es'},
        ),
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
