# Generated by Django 2.0.2 on 2019-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0030_test_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='mydidata.Test', verbose_name='Avaliações'),
        ),
    ]
