# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0031_auto_20180127_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
