# Generated by Django 2.0.2 on 2020-05-18 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0031_question_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado?'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Estudantes'),
        ),
    ]
