# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0032_discipline_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='discursiveanswer',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='assignments/%Y/%m/%d'),
        ),
    ]
