# Generated by Django 2.0.2 on 2020-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0032_auto_20200518_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='show_questions',
            field=models.BooleanField(default=True),
        ),
    ]
