# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 13:52
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0033_discursiveanswer_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discursiveanswer',
            name='answer_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='discursiveanswer',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='uploads/assignments/%Y/%m/%d'),
        ),
    ]
