# Generated by Django 2.0.2 on 2020-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0033_topic_show_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='limit_per_try',
            field=models.IntegerField(default=5),
        ),
    ]
