# Generated by Django 2.0.2 on 2020-05-22 20:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0034_test_limit_per_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_discursive',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texto da Alternativa'),
        ),
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ordem'),
        ),
    ]
