# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 15:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import mydidata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0034_auto_20180130_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discursiveanswer',
            name='answer_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discursiveanswer',
            name='assignment_file',
            field=models.FileField(null=True, storage=mydidata.models.OverwriteStorage(), upload_to='uploads/assignments/%Y/%m/%d'),
        ),
    ]
