# Generated by Django 2.0.2 on 2020-05-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0035_auto_20200522_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(),
        ),
    ]
