# Generated by Django 2.0.2 on 2020-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0036_auto_20200522_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_text',
            field=models.BooleanField(default=True),
        ),
    ]
