# Generated by Django 2.0.2 on 2020-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0037_question_has_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_assessment_question',
            field=models.BooleanField(default=True, verbose_name='Possui questão avaliativa?'),
        ),
    ]
