# Generated by Django 2.0.2 on 2020-05-26 22:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mydidata.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0038_topic_has_assessment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discursiveanswer',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='choice',
        ),
        migrations.DeleteModel(
            name='DiscursiveAnswer',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='answer',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, storage=mydidata.storage_backends.PublicMediaStorage(), upload_to='assignments/%Y/%m/%d', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Choice', verbose_name='Alternativa'),
        ),
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Correções'),
        ),

    ]
