# Generated by Django 2.0.2 on 2020-05-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0040_auto_20200527_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_text',
        ),
        migrations.AddField(
            model_name='question',
            name='file_upload_only',
            field=models.BooleanField(default=False, verbose_name='Aceitar somente upload de arquivos?'),
        ),
    ]
