# Generated by Django 2.0.2 on 2020-11-13 19:46

from django.db import migrations, models
import django.db.models.deletion
import mydidata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0041_auto_20200528_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_datetime', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Classroom')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mydidata.Topic', verbose_name='Tópico')),
            ],
            bases=(models.Model, mydidata.models.AdminURLMixin),
        ),
    ]
