# Generated by Django 2.0.2 on 2020-11-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0044_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='academic_site_id',
            field=models.IntegerField(default=0, verbose_name='Identificador no Acadêmico'),
        ),
    ]
