# Generated by Django 2.0.2 on 2020-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0045_classroom_academic_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
