# Generated by Django 2.0.2 on 2021-03-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0046_answer_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado/Desabilitado'),
        ),
        migrations.AddField(
            model_name='topic',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visível/Invisível'),
        ),
    ]
