# Generated by Django 2.0.2 on 2021-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0048_auto_20211023_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default='Variados', max_length=200, verbose_name='Tópico'),
        ),
    ]
