# Generated by Django 2.0.2 on 2021-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0049_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ref_keywords',
            field=models.TextField(blank=True, verbose_name='Palavras-Chave'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
    ]
