# Generated by Django 2.0.2 on 2021-12-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0050_auto_20211115_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='punish_copies',
            field=models.BooleanField(default=False, verbose_name='punir cópias exatas?'),
        ),
        migrations.AddField(
            model_name='question',
            name='punishment_percent',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Percentual da Punição'),
        ),
    ]
