# Generated by Django 2.0.2 on 2022-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0051_auto_20211228_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.TextField(null=True, verbose_name='Correções'),
        ),
    ]
