# Generated by Django 2.0.2 on 2022-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0052_auto_20220427_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_tries',
            field=models.IntegerField(default=2, verbose_name='Tentativas'),
        ),
        migrations.AddField(
            model_name='testuserrelation',
            name='tries',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Correções'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enviada'), (4, 'Reenviada'), (2, 'Excelente! (1.0)'), (5, 'Quase Perfeita (0.8)'), (7, 'Aceitável (0.6)'), (6, 'Apresenta muitos erros (0.3)'), (3, 'Errada (0.0)')], default=1, verbose_name='Avaliação'),
        ),
    ]
