# Generated by Django 2.0.2 on 2022-09-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0053_auto_20220817_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='Conteúdo relacionado à informática básica, técnicas de programação, desenvolvimento de apps', verbose_name='Descrição'),
        ),
    ]
