# Generated by Django 2.0.2 on 2022-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0054_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
