# Generated by Django 2.0.2 on 2022-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0055_topic_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rótulo'),
        ),
    ]
