# Generated by Django 2.0.2 on 2022-09-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0056_topic_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='saída esperada do programa (ou parte)'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_inputs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='entrada separa por vírgulas'),
        ),
    ]
