# Generated by Django 2.0.2 on 2022-12-11 20:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mydidata.models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0057_auto_20220930_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Versão')),
                ('version_of', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_version', to='mydidata.ContentVersion', verbose_name='Versão de')),
            ],
            bases=(models.Model, mydidata.models.AdminURLMixin),
        ),
        migrations.AddField(
            model_name='topic',
            name='latest_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydidata.ContentVersion', verbose_name='Última Versão'),
        ),
    ]
