# Generated by Django 2.0.2 on 2022-12-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0058_auto_20221211_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='version_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_version', to='mydidata.ContentVersion', verbose_name='Versão de'),
        ),
    ]
