# Generated by Django 2.0.2 on 2022-12-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0059_auto_20221211_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentversion',
            name='version_of',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='latest_version',
        ),
        migrations.AddField(
            model_name='contentversion',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='mydidata.Topic', verbose_name='Tópico'),
            preserve_default=False,
        ),
    ]
