# Generated by Django 2.0.2 on 2022-12-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0061_contentversion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentversion',
            name='number',
        ),
    ]
