# Generated by Django 2.0.2 on 2023-01-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0069_auto_20230118_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Peso'),
        ),
    ]
