# Generated by Django 2.0.2 on 2023-01-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0070_auto_20230123_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Classroom'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Topic', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='testuserrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testuserrelation',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydidata.Test'),
        ),
    ]
