# Generated by Django 2.0.2 on 2023-02-02 14:29

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mydidata.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0072_auto_20230129_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('publish_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mydidata.Topic', verbose_name='Postagem em Fórum')),
            ],
            bases=(models.Model, mydidata.models.AdminURLMixin),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resposta')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mydidata.ForumPost', verbose_name='Resposta')),
            ],
            bases=(models.Model, mydidata.models.AdminURLMixin),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mydidata.Question', verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='disciplines',
            field=models.ManyToManyField(null=True, related_name='classrooms', to='mydidata.Discipline', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='actions_log',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='mydidata.Topic', verbose_name='Tópico'),
        ),
    ]
