# Generated by Django 2.0.2 on 2023-02-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0074_auto_20230206_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Pontos Adquiridos'),
        ),
    ]
