# Generated by Django 2.0.2 on 2023-02-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0075_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='should_block_paste',
            field=models.BooleanField(default=True, verbose_name='Deseja impedir ações de copiar e colar nas respostas?'),
        ),
    ]
