# Generated by Django 2.0.2 on 2023-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0076_question_should_block_paste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='answer_points',
            field=models.IntegerField(default=0, verbose_name='pontos adquiridos em respostas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.CharField(default='', max_length=255, verbose_name='Medalhas Adquiridas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comment_points',
            field=models.IntegerField(default=0, verbose_name='Pontos Adquiridos em comentários'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_points',
            field=models.IntegerField(default=0, verbose_name='Pontos Adquiridos em Postagens no Fórum'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reply_points',
            field=models.IntegerField(default=0, verbose_name='Pontos Adquiridos em Respostas do Fórum'),
        ),
    ]
