# Generated by Django 2.0.2 on 2023-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0077_auto_20230209_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_badge_conquered',
            field=models.IntegerField(default=0, verbose_name='Última Medalha e Status'),
        ),
    ]
