# Generated by Django 2.0.2 on 2023-02-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0078_profile_last_badge_conquered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comments',
        ),
        migrations.AddField(
            model_name='answer',
            name='graphic_annotations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enviada'), (4, 'Reenviada'), (2, 'Excelente! (1.0)'), (5, 'Quase Perfeita (0.6 - 0.8)'), (7, 'Aceitável (0.3 - 0.6)'), (6, 'Apresenta muitos erros (0.1 - 0.3)'), (3, 'Errada (0.0)')], default=1, verbose_name='Avaliação'),
        ),
    ]
