# Generated by Django 2.0.2 on 2023-02-23 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mydidata', '0079_auto_20230218_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Professores'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='mydidata.Classroom'),
        ),
    ]
