# Generated by Django 2.0.2 on 2023-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydidata', '0080_auto_20230223_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alerts',
            field=models.TextField(blank=True, default='', verbose_name='Alertas'),
        ),
    ]
